name: "FIPS Release"

on:
  pull_request:
    branches:
      - "main"

permissions:
  contents: read

env:
  PLATFORMS: "linux_amd64"
  IMAGE_PLATFORMS: "linux/amd64"

jobs:
  lint:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f  # v4.1.3
      - uses: ./tools/github-actions/setup-deps
      - uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814  # v4.2.0
        with:
          version: v3.5.0
      # Generate the install manifests first so it can checked
      # for errors while running `make -k lint`
      - run: make generate-manifests
      - run: make lint-deps
      - run: make -k lint
